# Generated by Django 5.2.7 on 2025-10-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_portal_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=100)),
                ("medication_date", models.DateField()),
                ("medication_type", models.CharField(max_length=100)),
                ("medication_quantity", models.IntegerField()),
                ("medication_unit", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med_portal_backend.patient",
                    ),
                ),
            ],
        ),
    ]
