# Generated by Django 5.2.7 on 2025-10-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_portal_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_insurance", models.BooleanField()),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "insurance_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("card_expiry_month", models.IntegerField(blank=True, null=True)),
                ("card_expiry_year", models.IntegerField(blank=True, null=True)),
                (
                    "card_security_code",
                    models.IntegerField(blank=True, max_length=3, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med_portal_backend.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_date", models.DateField()),
                ("billing_amount", models.IntegerField()),
                ("billing_due_date", models.DateField()),
                (
                    "billing_card_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med_portal_backend.patient",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med_portal_backend.paymentmethod",
                    ),
                ),
            ],
        ),
    ]
