# Generated by Django 5.2.7 on 2025-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_portal_backend", "0002_paymentmethod_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_security_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
